name: Auto Tag

on:
  push:
    branches:
      - release  # Run this workflow on pushes to the main branch

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install setuptools setuptools_scm

      - name: Get version from setuptools_scm
        id: get_version
        run: |
          echo "version=$(python -m setuptools_scm)" >> "$GITHUB_ENV"

      - name: Configure Git Author
        run: |
            git config --global user.name "$GIT_AUTHOR_NAME"
            git config --global user.email "$GIT_AUTHOR_EMAIL"
      
      - name: Create Git Tag
        run: |
          git tag -a "$version" -m "Release version $version"
          git push origin --tags

  build_docker:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            tags: 4tu-codepublish/4tu-codepublish:latest
    